### ISSUE TITLE
get the error when yarn start

### ISSUE THREAD

**Issue by ashokj82** [RocketChat/Rocket.Chat.PWA#40]
ERROR TypeError: redux_persist_transform_immutable_1.default is not a function
    at eval (store.ts:26)
    at new ZoneAwarePromise (zone.js:834)
    at Object.exports.reduxPersist (store.ts:22)
    at eval (app.module.ts:18)
    at step (app.module.ts:38)
    at Object.eval [as next] (app.module.ts:19)
    at eval (app.module.ts:13)
    at new ZoneAwarePromise (zone.js:834)
    at __awaiter (app.module.ts:9)
    at Array.eval (app.module.ts:17)
defaultErrorLogger @ core.es5.js:1020
ErrorHandler.handleError @ core.es5.js:1080
(anonymous) @ core.es5.js:4409
ZoneDelegate.invoke @ zone.js:391
Zone.run @ zone.js:141
NgZone.runOutsideAngular @ core.es5.js:3844
(anonymous) @ core.es5.js:4409
ZoneDelegate.invoke @ zone.js:391
onInvoke @ core.es5.js:3890
ZoneDelegate.invoke @ zone.js:390
Zone.run @ zone.js:141
(anonymous) @ zone.js:818
ZoneDelegate.invokeTask @ zone.js:424
onInvokeTask @ core.es5.js:3881
ZoneDelegate.invokeTask @ zone.js:423
Zone.runTask @ zone.js:191
drainMicroTaskQueue @ zone.js:584
Promise.then (async)
scheduleMicroTask @ zone.js:567
ZoneDelegate.scheduleTask @ zone.js:413
Zone.scheduleTask @ zone.js:235
Zone.scheduleMicroTask @ zone.js:255
scheduleResolveOrReject @ zone.js:816
ZoneAwarePromise.then @ zone.js:905
PlatformRef_._bootstrapModuleWithZone @ core.es5.js:4537
PlatformRef_.bootstrapModule @ core.es5.js:4522
(anonymous) @ main.ts:19
./src/main.ts @ main.bundle.js:481
__webpack_require__ @ inline.bundle.js:55
0 @ main.bundle.js:489
__webpack_require__ @ inline.bundle.js:55
webpackJsonpCallback @ inline.bundle.js:26
(anonymous) @ main.bundle.js:1
zone.js:643 Unhandled Promise rejection: redux_persist_transform_immutable_1.default is not a function ; Zone: <root> ; Task: Promise.then ; Value: TypeError: redux_persist_transform_immutable_1.default is not a function
    at eval (store.ts:26)
    at new ZoneAwarePromise (zone.js:834)
    at Object.exports.reduxPersist (store.ts:22)
    at eval (app.module.ts:18)
    at step (app.module.ts:38)
    at Object.eval [as next] (app.module.ts:19)
    at eval (app.module.ts:13)
    at new ZoneAwarePromise (zone.js:834)
    at __awaiter (app.module.ts:9)
    at Array.eval (app.module.ts:17) TypeError: redux_persist_transform_immutable_1.default is not a function
    at eval (webpack-internal:///./src/app/shared/common/store.ts:16:65)
    at new ZoneAwarePromise (webpack-internal:///./node_modules/zone.js/dist/zone.js:834:29)
    at Object.exports.reduxPersist (webpack-internal:///./src/app/shared/common/store.ts:14:45)
    at eval (webpack-internal:///./src/app/app.module.ts:62:54)
    at step (webpack-internal:///./src/app/app.module.ts:38:23)
    at Object.eval [as next] (webpack-internal:///./src/app/app.module.ts:19:53)
    at eval (webpack-internal:///./src/app/app.module.ts:13:71)
    at new ZoneAwarePromise (webpack-internal:///./node_modules/zone.js/dist/zone.js:834:29)
    at __awaiter (webpack-internal:///./src/app/app.module.ts:9:12)
    at Array.eval (webpack-internal:///./src/app/app.module.ts:59:33)
api.onUnhandledError @ zone.js:643
handleUnhandledRejection @ zone.js:667
_loop_1 @ zone.js:658
api.microtaskDrainDone @ zone.js:662
drainMicroTaskQueue @ zone.js:592
Promise.then (async)
scheduleMicroTask @ zone.js:567
ZoneDelegate.scheduleTask @ zone.js:413
Zone.scheduleTask @ zone.js:235
Zone.scheduleMicroTask @ zone.js:255
scheduleResolveOrReject @ zone.js:816
ZoneAwarePromise.then @ zone.js:905
PlatformRef_._bootstrapModuleWithZone @ core.es5.js:4537
PlatformRef_.bootstrapModule @ core.es5.js:4522
(anonymous) @ main.ts:19
./src/main.ts @ main.bundle.js:481
__webpack_require__ @ inline.bundle.js:55
0 @ main.bundle.js:489
__webpack_require__ @ inline.bundle.js:55
webpackJsonpCallback @ inline.bundle.js:26
(anonymous) @ main.bundle.js:1
zone.js:645 Error: Uncaught (in promise): TypeError: redux_persist_transform_immutable_1.default is not a function
TypeError: redux_persist_transform_immutable_1.default is not a function
    at eval (store.ts:26)
    at new ZoneAwarePromise (zone.js:834)
    at Object.exports.reduxPersist (store.ts:22)
    at eval (app.module.ts:18)
    at step (app.module.ts:38)
    at Object.eval [as next] (app.module.ts:19)
    at eval (app.module.ts:13)
    at new ZoneAwarePromise (zone.js:834)
    at __awaiter (app.module.ts:9)
    at Array.eval (app.module.ts:17)
    at eval (store.ts:26)
    at new ZoneAwarePromise (zone.js:834)
    at Object.exports.reduxPersist (store.ts:22)
    at eval (app.module.ts:18)
    at step (app.module.ts:38)
    at Object.eval [as next] (app.module.ts:19)
    at eval (app.module.ts:13)
    at new ZoneAwarePromise (zone.js:834)
    at __awaiter (app.module.ts:9)
    at Array.eval (app.module.ts:17)
    at resolvePromise (zone.js:770)
    at eval (zone.js:696)
    at eval (zone.js:712)
    at ZoneDelegate.invoke (zone.js:391)
    at Zone.run (zone.js:141)
    at eval (zone.js:818)
    at ZoneDelegate.invokeTask (zone.js:424)
    at Zone.runTask (zone.js:191)
    at drainMicroTaskQueue (zone.js:584)
api.onUnhandledError @ zone.js:645
handleUnhandledRejection @ zone.js:667
_loop_1 @ zone.js:658
api.microtaskDrainDone @ zone.js:662
drainMicroTaskQueue @ zone.js:592
Promise.then (async)
scheduleMicroTask @ zone.js:567
ZoneDelegate.scheduleTask @ zone.js:413
Zone.scheduleTask @ zone.js:235
Zone.scheduleMicroTask @ zone.js:255
scheduleResolveOrReject @ zone.js:816
ZoneAwarePromise.then @ zone.js:905
PlatformRef_._bootstrapModuleWithZone @ core.es5.js:4537
PlatformRef_.bootstrapModule @ core.es5.js:4522
(anonymous) @ main.ts:19
./src/main.ts @ main.bundle.js:481
__webpack_require__ @ inline.bundle.js:55
0 @ main.bundle.js:489
__webpack_require__ @ inline.bundle.js:55
webpackJsonpCallback @ inline.bundle.js:26
(anonymous) @ main.bundle.js:1
client:147 [WDS] Warnings while compiling.
warnings @ client:147
onmessage @ socket.js:41
EventTarget.dispatchEvent @ sockjs.js:170
(anonymous) @ sockjs.js:887
SockJS._transportMessage @ sockjs.js:885
EventEmitter.emit @ sockjs.js:86
WebSocketTransport.ws.onmessage @ sockjs.js:2961
wrapFn @ zone.js:1056
ZoneDelegate.invokeTask @ zone.js:424
Zone.runTask @ zone.js:191
ZoneTask.invoke @ zone.js:486
client:153 ./node_modules/ionic-angular/util/ng-module-loader.js
27:11-36 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/ionic-angular/util/ng-module-loader.js
 @ ./node_modules/ionic-angular/module.js
 @ ./node_modules/ionic-angular/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://0.0.0.0:0 ./src/main.ts
warnings @ client:153
onmessage @ socket.js:41
EventTarget.dispatchEvent @ sockjs.js:170
(anonymous) @ sockjs.js:887
SockJS._transportMessage @ sockjs.js:885
EventEmitter.emit @ sockjs.js:86
WebSocketTransport.ws.onmessage @ sockjs.js:2961
wrapFn @ zone.js:1056
ZoneDelegate.invokeTask @ zone.js:424
Zone.runTask @ zone.js:191
ZoneTask.invoke @ zone.js:486
client:153 ./node_modules/ionic-angular/util/ng-module-loader.js
37:11-36 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/ionic-angular/util/ng-module-loader.js
 @ ./node_modules/ionic-angular/module.js
 @ ./node_modules/ionic-angular/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://0.0.0.0:0 ./src/main.ts
warnings @ client:153
onmessage @ socket.js:41
EventTarget.dispatchEvent @ sockjs.js:170
(anonymous) @ sockjs.js:887
SockJS._transportMessage @ sockjs.js:885
EventEmitter.emit @ sockjs.js:86
WebSocketTransport.ws.onmessage @ sockjs.js:2961
wrapFn @ zone.js:1056
ZoneDelegate.invokeTask @ zone.js:424
Zone.runTask @ zone.js:191
ZoneTask.invoke @ zone.js:486

**Comment by SmallShrimp** [comment]
why?
